services:
  api:
    build: .
    command: gunicorn "onfine.app_factory:create_app()" -b 0.0.0.0:5500 --worker-tmp-dir /dev/shm --workers 4
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "5500:5500"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=rRaW0-9gReSBC0NlNimyNQ

volumes:
  pgdata:
#
#
#services:
#  api:
#    build: .
#    env_file: .env
#    environment:
#      FLASK_APP: "onfine.app_factory:create_app"
#      FLASK_ENV: "development"   # если нужен авто-рестарт при изменении кода
#    volumes:
#      - .:/app
#    depends_on:
#      db:
#        condition: service_healthy
#      kafka:
#        condition: service_started
#    ports:
#      - "5500:5500"
#    command: >
#      sh -c "
#        # при старте подкатим миграции, затем запустим gunicorn
#        flask db upgrade &&
#        gunicorn 'onfine.app_factory:create_app()'
#          -b 0.0.0.0:5500
#          --workers 4
#      "
#
#  db:
#    image: postgres:16-alpine
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    restart: unless-stopped
#
#  kafka:
#    image: bitnami/kafka:3.7
#    environment:
#      - KAFKA_CFG_NODE_ID=0
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_KRAFT_CLUSTER_ID=rRaW0-9gReSBC0NlNimyNQ
#
#
#volumes:
#  pgdata: