FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .
RUN apk add --no-cache gcc musl-dev postgresql-dev libffi-dev openssl-dev \
 && pip install --upgrade pip \
 && pip install -r requirements.txt

COPY . .

CMD ["python", "onfine/email_consumer.py"]
