services:
  api:
    build: .
    command: gunicorn "onfine.app_factory:create_app()" -b 0.0.0.0:5500 --worker-tmp-dir /dev/shm --workers 4
    env_file: .env
    environment:
      - DOCKER_ENV=1
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "5500:5500"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094  # Доступ с хоста
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=rRaW0-9gReSBC0NlNimyNQ
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  # Автосоздание топиков при первом обращении
      - KAFKA_CREATE_TOPICS=balance_updates:1:1,transactions:1:1,erc20_transfers:1:1,bep20_transfers:1:1 # Топики, создаваемые при старте
      - KAFKA_CFG_NUM_PARTITIONS=3  # Дефолтное число партиций для новых топиков
      - KAFKA_CFG_LOG_RETENTION_HOURS=168  # Хранить данные 7 дней
    ports:
      - "9092:9092"  # Для внутреннего доступа (контейнеры)
      - "9094:9094"  # Для доступа с хоста (localhost)
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka-ui: #http://localhost:8080
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  email_consumer:
    build:
      context: .
      dockerfile: Dockerfile.email_consumer  # отдельный Dockerfile для консьюмера
    env_file: .env
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      ERROR_TOPIC: error_emails
      KAFKA_GROUP_ID: email_consumer_group
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  kafka_data: